# Generated by Django 4.1.3 on 2023-05-24 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0011_category_description_recipe_folder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
