# Generated by Django 4.1.3 on 2023-05-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_category_description_recipe_is_approved_and_more'),
    ]

    operations = []
